server:
  port: 8080

chatbot-api:
  owner: Shuo712
  repo: chatbot-api
  token: GITHUB_TOKEN
  deepseekApiKey: MY_DEEPSEEK_API_KEY
  deepseekModel: deepseek-chat

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

